(add-to-list 'load-path (concat user-emacs-directory "config"))
(add-to-list 'load-path (concat user-emacs-directory "config" "/elisp"))
(add-to-list 'load-path (concat user-emacs-directory "config" "/eyecandy"))
(add-to-list 'load-path (concat user-emacs-directory "config" "/languages"))

(setq package-archives '(("melpa" . "http://melpa.milkbox.net/packages/")
                         ("org" . "http://orgmode.org/elpa/")
                         ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(setq package-enable-at-startup nil)
(unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

;; Mute bytecode messages
(setq warning-minimum-level :emergency)

(require 'use-package)

(require 'my-core)
(require 'my-functions)
(require 'my-eyecandy)
(require 'my-dired)
(require 'my-buffers)
(require 'my-interaction)
(require 'my-ido)
(require 'my-helm)
(require 'my-comint)
(require 'my-languages)
(require 'my-flycheck)
(require 'my-magit)
(require 'my-copy)
(require 'my-eshell)
(require 'my-shell)
(require 'my-help)
(require 'my-woman)
;;(require 'my-paredit)
(require 'my-evil)
(require 'my-help)
(require 'my-god)
(require 'my-leader-keys)
(require 'my-emacspeak)

(provide 'init)
